### ISSUE TITLE
Check semver number against API change / infer right number bump

### ISSUE THREAD

**Issue by Apanatshka** [wraithan/cargo-bump#5]
I know this is way more complicated than the fairly simple tool that you have now, but consider checking the API of the crate and determining the semver number. It's not an unheared of feature, you can find this in the package tooling of the Elm programming language.

**Comment by wraithan** [comment]
That can get complex and wont cover cases like CLI tools, such as this one, so I'm not interested in ever adding this to cargo-bump. Feel encouraged to make your own if you'd like that functionality.
